# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           /:title/

# Setup
title:               OMG! Origami
tagline:             ''
description:         'Modelos en papel explicados paso a paso.'
host:                '0.0.0.0'
baseurl:             /

# About/contact
author:
  name:              facu.tk
  url:               https://facu.tk
  email:             facu.tk@gmail.com

# Custom vars
version:             1.0.0
google_analytics:    'UA-70318147-1'
models:              'public/origami/'